DROP TABLE IF EXISTS users_roles;
CREATE TABLE users_roles
(user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id),
 FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE);
INSERT INTO users_roles(USER_ID, ROLE_ID)
VALUES
    (1,2);

DROP TABLE IF EXISTS roles;
CREATE TABLE roles
(id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, name VARCHAR(45) NOT NULL);
INSERT INTO roles(ID, NAME)
VALUES
    (1,'ADMIN'),
    (2,'USER');